package require Tk

source opt_function.tcl



#-----------Window settings of the search engine---------------
grid [frame .opt.frame1  -pady 20 -padx 25] -columnspan 6 -row 1 -sticky wens
grid [label .opt.frame1.wavelbl -text "Wavelength(nm)"] -column 3 -row 1 -sticky w
grid [label .opt.frame1.orglbl -text "Organ" ] -column 1 -row 1 -sticky w
grid [label .opt.frame1.spelbl -text "Species" ] -column 1 -row 3 -sticky w
grid [label .opt.frame1.uclbl -text "Uncertainty"] -column 3 -row 2 -sticky w
grid [label .opt.frame1.sttlbl -text "Status"] -column 1 -row 2 -sticky w

grid [ttk::spinbox .opt.frame1.wlval -textvariable wavelength -from 100.0 -to 1500.0 -increment 1] -column 4 -row 1 -sticky w
grid [ttk::combobox .opt.frame1.organval -values [list air bladder blood bone brain breast fat gray_matter heart liver lung muscle skin water white_matter] -textvariable organ] -column 2 -row 1 -sticky w
grid [ttk::combobox .opt.frame1.speciesval -values [list human rat mouse rabbit pig none] -textvariable species] -column 2 -row 3 -sticky w
grid [ttk::spinbox .opt.frame1.ucval  -textvariable uncertainty -from 1.0 -to 200.0 -increment 1] -column 4 -row 2 -sticky w
grid [ttk::combobox .opt.frame1.sttval -values [list healthy tumor none] -textvariable status] -column 2 -row 2 -sticky w

grid [button .opt.frame1.search -text "Search" -command search] -column 4 -row 4 -sticky e




#-----------Window settings of the results generated by the search engine(with its own frame)---------------
grid configure [frame .opt.frame2  -pady 20 -padx 25 ] -columnspan 3 -row 2 -sticky we

grid [label .opt.frame2.albl -text "mu_a"] -column 2 -row 1 -padx 20 -sticky w
grid [label .opt.frame2.slbl -text "mu_s" ] -column 3 -row 1 -padx 20 -sticky w
grid [label .opt.frame2.slbl1 -text "mu_s'"] -column 4 -row 1 -padx 20 -sticky w
grid [label .opt.frame2.glbl -text "g"] -column 5 -row 1 -padx 20 -sticky w
grid [label .opt.frame2.nlbl -text "n"] -column 6 -row 1 -padx 20 -sticky w
grid [label .opt.frame2.avglbl -text "Average"] -column 1 -row 2 -padx 5 -sticky w
grid [label .opt.frame2.minlbl -text "Min" ] -column 1 -row 3 -padx 5 -sticky w
grid [label .opt.frame2.maxlbl -text "Max" ] -column 1 -row 4 -padx 5 -sticky w

grid [ttk::label .opt.frame2.avg_a -textvariable avg_a ] -column 2 -row 2 -padx 5 -sticky we
grid [ttk::label .opt.frame2.avg_s -textvariable avg_s ] -column 3 -row 2 -padx 5 -sticky we
grid [ttk::label .opt.frame2.avg_s1 -textvariable avg_s1 ] -column 4 -row 2 -padx 5 -sticky we
grid [ttk::label .opt.frame2.avg_g -textvariable avg_g ] -column 5 -row 2 -padx 5 -sticky we
grid [ttk::label .opt.frame2.avg_n -textvariable avg_n ] -column 6 -row 2 -padx 5 -sticky we

grid [ttk::label .opt.frame2.min_a -textvariable min_a ] -column 2 -row 3 -padx 5 -sticky we
grid [ttk::label .opt.frame2.min_s -textvariable min_s ] -column 3 -row 3 -padx 5 -sticky we
grid [ttk::label .opt.frame2.min_s1 -textvariable min_s1 ] -column 4 -row 3 -padx 5 -sticky we
grid [ttk::label .opt.frame2.min_g -textvariable min_g ] -column 5 -row 3 -padx 5 -sticky we
grid [ttk::label .opt.frame2.min_n -textvariable min_n  ] -column 6 -row 3 -padx 5 -sticky we

grid [ttk::label .opt.frame2.max_a -textvariable max_a ] -column 2 -row 4 -padx 5 -sticky we
grid [ttk::label .opt.frame2.max_s -textvariable max_s ] -column 3 -row 4 -padx 5 -sticky we
grid [ttk::label .opt.frame2.max_s1 -textvariable max_s1 ] -column 4 -row 4 -padx 5 -sticky we
grid [ttk::label .opt.frame2.max_g -textvariable max_g ] -column 5 -row 4 -padx 5 -sticky we
grid [ttk::label .opt.frame2.max_n -textvariable max_n ] -column 6 -row 4 -padx 5 -sticky we

grid [button .opt.frame2.allopt -text "Show All" -command ShowAllOpt] -column 7 -row 4 -padx 40 -sticky we



#-----------Window settings of the opt file generator---------------
grid configure [frame .opt.frame3  -pady 20 -padx 25 ] -columnspan 3 -row 3 -sticky we
grid [button .opt.frame3.generatefile -text "Generate/Overwrite an opt file with name:" -command generate] -column 1 -row 1 -sticky we
grid [entry .opt.frame3.filename -textvariable fname ] -column 2 -row 1 -sticky we

grid [button .opt.frame3.nborgan -text "Set number of total organs:" -command SetOrgan] -column 1 -row 2 -sticky we
grid [entry .opt.frame3.norgans -textvariable norgan ] -column 2 -row 2 -sticky we

grid [button .opt.frame3.addopt -text "Add current property to file" -command AddOpt] -column 1 -row 3 -sticky we

grid [button .opt.frame3.deleteopt -text "Delete last line" -command DeleteOpt] -column 1 -row 4 -sticky we

grid [button .opt.frame3.closefile -text "Finish opt file" -command FinishOpt] -column 1 -row 5 -sticky we

grid configure [label .opt.frame3.filedis -textvariable filedis ] -rowspan 6 -column 3 -row 1 -sticky w


#-----------Window settings of the Database editor button---------------
grid configure [frame .opt.frame4  -pady 20 -padx 350 ] -columnspan 3 -row 4 -sticky wen
grid [button .opt.frame4.database -text "Edit Database" -command MakeDatabase] -column 2 -row 1 -padx 100 -sticky e



